const EQUIPMENT_LIBRARY = {
  alarm: {
    name: "أنظمة الإنذار",
    icon: "A",
    groups: {
      "لوحات التحكم": [
        { name: "لوحة تحكم إنذار حريق تقليدية 2 منطقة", supply: 850, install: 600 },
        { name: "لوحة تحكم إنذار حريق تقليدية 4 مناطق", supply: 1400, install: 700 },
        { name: "لوحة تحكم إنذار حريق تقليدية 8 مناطق", supply: 2200, install: 900 },
        { name: "لوحة تحكم إنذار حريق تقليدية 16 منطقة", supply: 3600, install: 1200 },
        { name: "لوحة تحكم إنذار حريق تقليدية 32 منطقة", supply: 6200, install: 1500 },
        { name: "لوحة تكرارية تقليدية (Repeater) 8 مناطق", supply: 2500, install: 700 },
        { name: "لوحة تحكم إنذار حريق معنونة (Addressable) حلقة واحدة", supply: 6800, install: 1800 },
        { name: "لوحة تحكم إنذار حريق معنونة حلقتان", supply: 12500, install: 2200 },
        { name: "لوحة تحكم معنونة 4 حلقات", supply: 21000, install: 2800 },
        { name: "لوحة تكرارية معنونة (Repeater Panel)", supply: 4500, install: 900 },
        { name: "وحدة توسعة مناطق إضافية (Zone Expander)", supply: 800, install: 200 },
        { name: "وحدة حلقة إضافية (Loop Card)", supply: 2200, install: 350 },
        { name: "جهاز عرض مناطق منفصل (ANN/Zone Annunciator)", supply: 420, install: 120 },
        { name: "بطارية احتياطية للوحة 12 فولت 7 أمبير", supply: 150, install: 0 },
        { name: "بطارية احتياطية 12 فولت 17 أمبير", supply: 280, install: 0 },
        { name: "بطارية احتياطية 12 فولت 40 أمبير", supply: 620, install: 0 },
        { name: "شاحن بطاريات مستقل 24 فولت", supply: 950, install: 250 },
        { name: "خزانة لوحة إنذار خارجية مقاومة للعوامل", supply: 1800, install: 300 }
      ],
      "الكواشف التقليدية": [
        { name: "كاشف دخان تقليدي (Smoke Detector)", supply: 120, install: 55 },
        { name: "كاشف حرارة تقليدي (Heat Detector)", supply: 95, install: 55 },
        { name: "كاشف حرارة ثابتة ومعدل الارتفاع (ROR)", supply: 110, install: 55 },
        { name: "كاشف دخان خطي (Beam Detector) - زوج كامل", supply: 4200, install: 600 },
        { name: "كاشف لهب تقليدي (Flame Detector)", supply: 4800, install: 700 },
        { name: "كاشف غاز أول أكسيد الكربون تقليدي", supply: 850, install: 120 },
        { name: "كاشف دخان بقنوات التكييف (Duct Detector)", supply: 1500, install: 350 },
        { name: "كاشف دخان مدمج مع قاعدة عزل", supply: 180, install: 60 }
      ],
      "الكواشف المعنونة": [
        { name: "كاشف دخان معنون (Addressable Smoke Detector)", supply: 320, install: 65 },
        { name: "كاشف حرارة معنون (Addressable Heat Detector)", supply: 290, install: 65 },
        { name: "كاشف دخان معنون متعدد الحساسية (Multi-criteria)", supply: 520, install: 70 },
        { name: "كاشف حرارة معنون ROR", supply: 310, install: 65 },
        { name: "كاشف لهب معنون (Addressable Flame)", supply: 8500, install: 900 },
        { name: "كاشف دخان خطي معنون", supply: 5600, install: 700 },
        { name: "كاشف دخان معنون للقنوات (Addressable Duct)", supply: 1900, install: 380 },
        { name: "كاشف غاز معنون", supply: 1200, install: 150 }
      ],
      "نقاط الاستدعاء اليدوية": [
        { name: "نقطة استدعاء يدوية تقليدية (Manual Call Point)", supply: 85, install: 45 },
        { name: "نقطة استدعاء يدوية معنونة (Addressable MCP)", supply: 230, install: 50 },
        { name: "نقطة استدعاء يدوية مقاومة للماء IP67", supply: 160, install: 55 },
        { name: "نقطة استدعاء بلمسة زجاجية للأسطح الخطرة", supply: 190, install: 50 },
        { name: "مفتاح اختبار يدوي للنقاط", supply: 45, install: 25 }
      ],
      "أجهزة التنبيه والإعلان": [
        { name: "جرس إنذار داخلي 6 بوصة", supply: 75, install: 40 },
        { name: "جرس إنذار خارجي مقاوم للماء", supply: 140, install: 50 },
        { name: "صفارة إنذار (Horn/Sounder)", supply: 130, install: 45 },
        { name: "لمبة وميض (Strobe Light)", supply: 110, install: 45 },
        { name: "وحدة صوت وضوء (Sounder + Strobe)", supply: 240, install: 55 },
        { name: "صفارة جدارية معنونة (Addressable Sounder)", supply: 330, install: 55 },
        { name: "وحدة صوت/ضوء معنونة", supply: 420, install: 60 },
        { name: "جرس إنذار بجهد منخفض لذوي الاحتياجات (VAD)", supply: 350, install: 55 },
        { name: "صافرة إنذار مائية (Water Motor Gong)", supply: 500, install: 120 }
      ],
      "الوحدات والملحقات المعنونة": [
        { name: "وحدة مراقبة معنونة (Monitor Module)", supply: 260, install: 55 },
        { name: "وحدة تحكم معنونة (Control Module)", supply: 280, install: 60 },
        { name: "وحدة مراقبة/تحكم مدمجة (Combined Module)", supply: 300, install: 60 },
        { name: "وحدة عزل حلقة (Isolator Module)", supply: 200, install: 40 },
        { name: "وحدة مرحلات 2 قناة (2-Relay Module)", supply: 380, install: 70 },
        { name: "وحدة مراقبة تدفق مائي (Flow Switch Module)", supply: 240, install: 60 },
        { name: "وحدة مراقبة ضغط (Pressure Switch Module)", supply: 240, install: 60 },
        { name: "وحدة إدخال/إخراج عامة (I/O Module)", supply: 320, install: 60 },
        { name: "صندوق تركيب وحدة (Module Enclosure)", supply: 45, install: 25 },
        { name: "محول طاقة مستقل 24 فولت للوحدات", supply: 400, install: 120 }
      ],
      "قواعد الكواشف والملحقات": [
        { name: "قاعدة كاشف قياسية (Detector Base)", supply: 25, install: 0 },
        { name: "قاعدة كاشف مع مقاومة عزل (Relay Base)", supply: 60, install: 0 },
        { name: "قاعدة كاشف معنونة مع عزل", supply: 90, install: 0 },
        { name: "مركب كاشف في السقف (Detector Recess/Trim)", supply: 35, install: 0 },
        { name: "غطاء واقي للكاشف أثناء العمل", supply: 15, install: 0 },
        { name: "مفتاح مفتاح مقص (Key Switch) لإعادة التعيين", supply: 60, install: 30 },
        { name: "لوحة سحب رئيسية بالموقع (Panel Key Switch)", supply: 80, install: 40 },
        { name: "عاكس الحماية من الرطوبة (Weather-proof Backbox)", supply: 70, install: 30 }
      ],
      "الكابلات والتمديدات": [
        { name: "كابل مقاوم للحريق 2 نواة (لفة 100م)", supply: 420, install: 0 },
        { name: "كابل مقاوم للحريق 4 نواة (لفة 100م)", supply: 720, install: 0 },
        { name: "كابل مقاوم للحريق 6 نواة (لفة 100م)", supply: 1080, install: 0 },
        { name: "كابل حلقة معنونة زوج مجدول (لفة 300م)", supply: 1400, install: 0 },
        { name: "كابل مقاوم للحريق 8 نواة (لفة 100م)", supply: 1500, install: 0 },
        { name: "كابل شبكة RS485 للوحات التكرارية (م/متر)", supply: 6, install: 3 },
        { name: "كابل كشف دخان خطي (م/متر)", supply: 30, install: 5 },
        { name: "كابل تغذية 2×1.5مم (لفة 100م)", supply: 180, install: 0 },
        { name: "كابل تغذية 3×2.5مم (لفة 100م)", supply: 300, install: 0 }
      ],
      "مواسير التمديدات وعلب التوزيع": [
        { name: "ماسورة PVC سميكة 20مم (م/متر)", supply: 5, install: 4 },
        { name: "ماسورة PVC سميكة 25مم (م/متر)", supply: 7, install: 4 },
        { name: "ماسورة حديد مرنة (Flexible Conduit) 20مم (م/متر)", supply: 12, install: 6 },
        { name: "ماسورة حديد مرنة 25مم (م/متر)", supply: 16, install: 7 },
        { name: "ماسورة حديد مجلفن EMT 20مم (م/متر)", supply: 18, install: 8 },
        { name: "علبة توزيع PVC 4×4", supply: 12, install: 10 },
        { name: "علبة توزيع حديد 4×4", supply: 28, install: 12 },
        { name: "علبة سقفية للكاشف (Junction Box)", supply: 10, install: 8 },
        { name: "كوع/مشبك PVC 20مم", supply: 2, install: 0 },
        { name: "مشبك تثبيت ماسورة (Pipe Clip)", supply: 1.5, install: 0 },
        { name: "قناة كابلات (Cable Tray) معدنية (م/متر)", supply: 85, install: 35 }
      ],
      "أجهزة الاختبار والقياس": [
        { name: "أداة اختبار الكواشف (Test Tool - أيروسول)", supply: 150, install: 0 },
        { name: "علبة غاز اختبار الكواشف", supply: 85, install: 0 },
        { name: "مقياس مقاومة العزل (Insulation Tester)", supply: 900, install: 0 },
        { name: "جهاز برمجة الكواشف المعنونة (Programmer)", supply: 650, install: 0 },
        { name: "مولد صوت لاختبار صفارات الانذار", supply: 250, install: 0 }
      ]
    }
  },

  fighting: {
    name: "أنظمة الإطفاء",
    icon: "F",
    groups: {
      "الإطفاء اليدوي (طفايات وخزائن)": [
        { name: "طفاية بودرة جافة 6 كجم ABC", supply: 85, install: 15 },
        { name: "طفاية بودرة جافة 9 كجم ABC", supply: 120, install: 15 },
        { name: "طفاية بودرة جافة 12 كجم ABC", supply: 165, install: 20 },
        { name: "طفاية بودرة جافة 25 كجم ABC (عجلات)", supply: 850, install: 40 },
        { name: "طفاية CO2 ثاني أكسيد الكربون 5 كجم", supply: 320, install: 20 },
        { name: "طفاية CO2 9 كجم", supply: 520, install: 25 },
        { name: "طفاية مياه 9 لتر", supply: 180, install: 15 },
        { name: "طفاية رغوة 9 لتر", supply: 240, install: 15 },
        { name: "طفاية كيميائية سائلة (Wet Chemical) للزيوت 6 لتر", supply: 420, install: 20 },
        { name: "طفاية سلسلة الإطفاء بالبطاريات الليثيوم", supply: 780, install: 20 },
        { name: "خزانة طفاية حائط (Cabinet) زجاج أمامي", supply: 120, install: 40 },
        { name: "خزانة طفاية حائط معدنية بالكامل", supply: 180, install: 50 },
        { name: "طقم طفاية كامل مع خزانة وحامل", supply: 250, install: 60 },
        { name: "حامل أرضي للطفاية", supply: 45, install: 20 },
        { name: "علامة دلالية + ملصق تعليمات", supply: 60, install: 20 },
        { name: "مشبك تثبيت طفاية في المركبات/المعدات", supply: 35, install: 15 }
      ],
      "شبكة المواسير (أنابيب الحريق)": [
        { name: "ماسورة حديد مجلفن (GI) قطر 1 بوصة (م/متر)", supply: 38, install: 12 },
        { name: "ماسورة حديد مجلفن (GI) قطر 1.25 بوصة (م/متر)", supply: 48, install: 13 },
        { name: "ماسورة حديد مجلفن (GI) قطر 1.5 بوصة (م/متر)", supply: 60, install: 14 },
        { name: "ماسورة حديد مجلفن (GI) قطر 2 بوصة (م/متر)", supply: 78, install: 16 },
        { name: "ماسورة حديد مجلفن (GI) قطر 2.5 بوصة (م/متر)", supply: 105, install: 18 },
        { name: "ماسورة حديد مجلفن (GI) قطر 3 بوصة (م/متر)", supply: 135, install: 20 },
        { name: "ماسورة حديد مجلفن (GI) قطر 4 بوصة (م/متر)", supply: 185, install: 24 },
        { name: "ماسورة حديد مجلفن (GI) قطر 6 بوصة (م/متر)", supply: 330, install: 32 },
        { name: "ماسورة حديد أسود ملحومة (Black Steel) 2 بوصة (م/متر)", supply: 72, install: 16 },
        { name: "ماسورة حديد أسود 3 بوصة (م/متر)", supply: 125, install: 20 },
        { name: "ماسورة حديد أسود 4 بوصة (م/متر)", supply: 170, install: 24 },
        { name: "ماسورة حديد أسود 6 بوصة (م/متر)", supply: 300, install: 32 },
        { name: "ماسورة CPVC للأطفاء بالرشاشات 25مم (م/متر)", supply: 28, install: 8 },
        { name: "ماسورة CPVC 50مم (م/متر)", supply: 55, install: 10 },
        { name: "ماسورة CPVC 100مم (م/متر)", supply: 140, install: 14 },
        { name: "ماسورة HDPE للتغذية الخارجية 63مم (م/متر)", supply: 45, install: 8 },
        { name: "ماسورة HDPE 90مم (م/متر)", supply: 85, install: 10 },
        { name: "ماسورة HDPE 110مم (م/متر)", supply: 120, install: 12 }
      ],
      "التوصيلات (أكواع - تيه - نقاصات)": [
        { name: "كوع 90° مجلفن قطر 1 بوصة", supply: 12, install: 0 },
        { name: "كوع 90° مجلفن قطر 1.5 بوصة", supply: 20, install: 0 },
        { name: "كوع 90° مجلفن قطر 2 بوصة", supply: 28, install: 0 },
        { name: "كوع 90° مجلفن قطر 3 بوصة", supply: 48, install: 0 },
        { name: "كوع 90° مجلفن قطر 4 بوصة", supply: 75, install: 0 },
        { name: "كوع 90° مجلفن قطر 6 بوصة", supply: 160, install: 0 },
        { name: "كوع 45° مجلفن قطر 2 بوصة", supply: 24, install: 0 },
        { name: "كوع 45° مجلفن قطر 3 بوصة", supply: 40, install: 0 },
        { name: "كوع 45° مجلفن قطر 4 بوصة", supply: 62, install: 0 },
        { name: "تيه (TEE) مجلفن قطر 1 بوصة", supply: 18, install: 0 },
        { name: "تيه (TEE) مجلفن قطر 1.5 بوصة", supply: 30, install: 0 },
        { name: "تيه (TEE) مجلفن قطر 2 بوصة", supply: 42, install: 0 },
        { name: "تيه (TEE) مجلفن قطر 3 بوصة", supply: 72, install: 0 },
        { name: "تيه (TEE) مجلفن قطر 4 بوصة", supply: 110, install: 0 },
        { name: "تيه (TEE) مجلفن قطر 6 بوصة", supply: 240, install: 0 },
        { name: "نقاص (Reducer) 2 إلى 1.5 بوصة", supply: 22, install: 0 },
        { name: "نقاص (Reducer) 2 إلى 1 بوصة", supply: 20, install: 0 },
        { name: "نقاص (Reducer) 3 إلى 2 بوصة", supply: 35, install: 0 },
        { name: "نقاص (Reducer) 4 إلى 3 بوصة", supply: 58, install: 0 },
        { name: "نقاص (Reducer) 6 إلى 4 بوصة", supply: 130, install: 0 },
        { name: "وصلة (Coupling) مجلفن قطر 1 بوصة", supply: 10, install: 0 },
        { name: "وصلة (Coupling) مجلفن قطر 2 بوصة", supply: 20, install: 0 },
        { name: "وصلة (Coupling) مجلفن قطر 3 بوصة", supply: 38, install: 0 },
        { name: "وصلة (Coupling) مجلفن قطر 4 بوصة", supply: 60, install: 0 },
        { name: "صامولة وصل (Union) قطر 1 بوصة", supply: 22, install: 0 },
        { name: "صامولة وصل (Union) قطر 2 بوصة", supply: 45, install: 0 },
        { name: "حلمة (Nipple) قطر 1 بوصة × 10سم", supply: 8, install: 0 },
        { name: "حلمة (Nipple) قطر 2 بوصة × 10سم", supply: 16, install: 0 },
        { name: "غطاء نهاية (Cap) قطر 1 بوصة", supply: 8, install: 0 },
        { name: "غطاء نهاية (Cap) قطر 2 بوصة", supply: 15, install: 0 },
        { name: "غطاء نهاية (Cap) قطر 4 بوصة", supply: 45, install: 0 },
        { name: "فلنجة (Flange) قطر 4 بوصة مع طقم براغي", supply: 120, install: 30 },
        { name: "فلنجة (Flange) قطر 6 بوصة مع طقم براغي", supply: 220, install: 40 },
        { name: "وصلة Groove (Victaulic) قطر 2 بوصة", supply: 90, install: 15 },
        { name: "وصلة Groove (Victaulic) قطر 4 بوصة", supply: 160, install: 20 },
        { name: "وصلة Groove (Victaulic) قطر 6 بوصة", supply: 280, install: 30 },
        { name: "كوع Groove قطر 4 بوصة", supply: 180, install: 25 },
        { name: "تيه Groove قطر 4 بوصة", supply: 240, install: 30 },
        { name: "لصق CPVC + منظف (مجموعة)", supply: 45, install: 0 }
      ],
      "العلاقات والمثبتات": [
        { name: "علاقة ماسورة بسيطة (Pipe Hanger) قطر 1 بوصة", supply: 8, install: 0 },
        { name: "علاقة ماسورة بسيطة قطر 1.5 بوصة", supply: 10, install: 0 },
        { name: "علاقة ماسورة بسيطة قطر 2 بوصة", supply: 12, install: 0 },
        { name: "علاقة ماسورة بسيطة قطر 3 بوصة", supply: 18, install: 0 },
        { name: "علاقة ماسورة بسيطة قطر 4 بوصة", supply: 28, install: 0 },
        { name: "علاقة ماسورة بسيطة قطر 6 بوصة", supply: 55, install: 0 },
        { name: "حمالة على شكل U (U-Bolt) قطر 2 بوصة", supply: 16, install: 0 },
        { name: "حمالة U-Bolt قطر 3 بوصة", supply: 24, install: 0 },
        { name: "حمالة U-Bolt قطر 4 بوصة", supply: 38, install: 0 },
        { name: "قناة حديدية للتركيب (Strut Channel) 41×41 (م/متر)", supply: 25, install: 6 },
        { name: "ركازة/قاعدة قناة (Channel Base)", supply: 30, install: 10 },
        { name: "مشبك قناة (Channel Clamp)", supply: 12, install: 0 },
        { name: "قضيب تعليق (Threaded Rod) 10مم (م/متر)", supply: 8, install: 0 },
        { name: "صامولة قناة (Channel Nut) مع برغي", supply: 4, install: 0 },
        { name: "بلاطة تثبيت (Anchor Plate)", supply: 15, install: 8 },
        { name: "مسامير تثبيت خرسانة (Expansion Bolt) طقم", supply: 3, install: 0 },
        { name: "علاقة حدادة ملحومة حسب التصميم", supply: 35, install: 15 }
      ],
      "المحابس والصمامات": [
        { name: "محبس بوابة (Gate Valve) قطر 1.5 بوصة", supply: 95, install: 40 },
        { name: "محبس بوابة (Gate Valve) قطر 2 بوصة", supply: 130, install: 50 },
        { name: "محبس بوابة (Gate Valve) قطر 3 بوصة", supply: 250, install: 70 },
        { name: "محبس بوابة (Gate Valve) قطر 4 بوصة", supply: 450, install: 90 },
        { name: "محبس بوابة (Gate Valve) قطر 6 بوصة", supply: 900, install: 130 },
        { name: "محبس OS&Y قطر 2 بوصة", supply: 650, install: 200 },
        { name: "محبس OS&Y قطر 4 بوصة", supply: 1600, install: 300 },
        { name: "محبس OS&Y قطر 6 بوصة", supply: 3200, install: 400 },
        { name: "محبس فراشة (Butterfly Valve) قطر 4 بوصة", supply: 850, install: 150 },
        { name: "محبس فراشة (Butterfly Valve) قطر 6 بوصة", supply: 1500, install: 200 },
        { name: "محبس عدم رجوع (Check Valve) قطر 2 بوصة", supply: 220, install: 60 },
        { name: "محبس عدم رجوع (Check Valve) قطر 3 بوصة", supply: 380, install: 80 },
        { name: "محبس عدم رجوع (Check Valve) قطر 4 بوصة", supply: 620, install: 100 },
        { name: "منظم ضغط (Pressure Reducing Valve) قطر 2.5 بوصة", supply: 1500, install: 250 },
        { name: "منظم ضغط (PRV) قطر 4 بوصة", supply: 3200, install: 350 },
        { name: "صمام تنفيس (Relief Valve) قطر 1 بوصة", supply: 160, install: 40 },
        { name: "صمام هواء (Air Release Valve) قطر 1 بوصة", supply: 120, install: 35 },
        { name: "صمام إنذار تدفق مائي (Alarm Check Valve) قطر 4 بوصة", supply: 2600, install: 400 },
        { name: "غرفة تأخير (Retard Chamber)", supply: 450, install: 120 },
        { name: "صمام تحكم منطقة (Zone Control Valve)", supply: 420, install: 90 }
      ],
      "رشاشات ومكوناتها": [
        { name: "رشاش مياه مخفي (Concealed) 1/2 بوصة", supply: 65, install: 45 },
        { name: "رشاش مياه علوي (Upright) 1/2 بوصة", supply: 55, install: 45 },
        { name: "رشاش مياه سفلي (Pendent) 1/2 بوصة", supply: 60, install: 45 },
        { name: "رشاش مياه جنبي (Sidewall) 1/2 بوصة", supply: 70, install: 45 },
        { name: "رشاش استجابة سريعة (Quick Response)", supply: 80, install: 50 },
        { name: "رشاش لمخاطر عالية (Extra Hazard)", supply: 160, install: 60 },
        { name: "رشاش مقاوم للتآكل (Corrosion Resistant)", supply: 190, install: 55 },
        { name: "مركب رشاش (Sprinkler Reducer Coupling)", supply: 18, install: 0 },
        { name: "رافعة رشاش (Drop Nipple) 1/2 × 15سم", supply: 25, install: 0 },
        { name: "رافعة رشاش 1/2 × 30سم", supply: 35, install: 0 },
        { name: "صينية/غلاف رشاش (Escutcheon)", supply: 8, install: 0 },
        { name: "جهاز إنذار تدفق المياه (Flow Switch)", supply: 380, install: 90 },
        { name: "جهاز مراقبة ضغط (Pressure Switch)", supply: 320, install: 80 },
        { name: "مقياس ضغط (Pressure Gauge)", supply: 45, install: 20 },
        { name: "قابس تصريف (Drain Valve) قطر 2 بوصة", supply: 140, install: 50 },
        { name: "صمام اختبار (Test & Drain Valve)", supply: 220, install: 60 }
      ],
      "أنظمة الخراطيم والصنابير": [
        { name: "صندوق حريق داخلي (Fire Hose Cabinet) مدمج مع خرطوم", supply: 850, install: 150 },
        { name: "صندوق حريق داخلي مع خرطوم ومفتاح ومخروط", supply: 1200, install: 200 },
        { name: "خرطوم حريق داخلي 25م مع فوهة", supply: 650, install: 80 },
        { name: "خرطوم حريق داخل 30م", supply: 750, install: 90 },
        { name: "مفتاح حريق (Fire Hose Valve) قطر 1.5 بوصة", supply: 280, install: 60 },
        { name: "مفتاح حريق قطر 2.5 بوصة", supply: 450, install: 80 },
        { name: "فوهة خرطوم (Nozzle) مزدوجة", supply: 180, install: 0 },
        { name: "وصلة خرطوم (Hose Coupling)", supply: 60, install: 0 },
        { name: "صنبور حريق خارجي (Fire Hydrant)", supply: 950, install: 300 },
        { name: "صنبور خارجي بأعمدة (Post Hydrant)", supply: 2200, install: 600 },
        { name: "صندوق حريق خارجي مجهز (Fire Department Connection)", supply: 2800, install: 700 },
        { name: "مرشح شوائب (Strainer) قطر 4 بوصة", supply: 450, install: 100 },
        { name: "صمام ربط معدن (Siamese Connection)", supply: 1200, install: 250 }
      ],
      "مضخات الحريق": [
        { name: "مضخة حريق رئيسية كهربائية 25 ل/ث - حسب المواصفات", supply: 0, install: 0 },
        { name: "مضخة حريق احتياطية ديزل 25 ل/ث - حسب المواصفات", supply: 0, install: 0 },
        { name: "مضخة معززة (Jockey Pump)", supply: 7500, install: 1500 },
        { name: "لوحة تحكم مضخة كهربائية (Starter Panel)", supply: 4500, install: 800 },
        { name: "لوحة تحكم مضخة ديزل (Diesel Controller)", supply: 5500, install: 900 },
        { name: "جهاز انتقال تلقائي ATS", supply: 4800, install: 700 },
        { name: "خزان حريق أفقي 1000 لتر", supply: 3500, install: 800 },
        { name: "خزان حريق أفقي 5000 لتر", supply: 12000, install: 1500 },
        { name: "خزان حريق عمودي 10000 لتر", supply: 20000, install: 2200 },
        { name: "صمام إدخال مياه البلدية (City Inlet)", supply: 1800, install: 400 },
        { name: "عدّاد تدفق (Flow Meter)", supply: 650, install: 150 }
      ],
      "أنظمة الإطفاء بالغاز": [
        { name: "نظام إطفاء غاز FM200 - تصميم حسب حجم الغرفة", supply: 0, install: 0 },
        { name: "صهريج غاز FM200 45 لتر", supply: 14000, install: 1500 },
        { name: "صهريج غاز FM200 90 لتر", supply: 22000, install: 2000 },
        { name: "صهريج غاز CO2 50 كجم", supply: 9000, install: 1200 },
        { name: "صهريج غاز CO2 100 كجم", supply: 16000, install: 1800 },
        { name: "مجموعة فوهات إطلاق الغاز (Discharge Nozzles)", supply: 350, install: 80 },
        { name: "صمام إطلاق (Discharge Valve)", supply: 850, install: 200 },
        { name: "لوحة تحكم إطفاء غاز (Gas Panel)", supply: 3200, install: 600 },
        { name: "جهاز إنذار بصوت قبل الإطلاق (Pneumatic Horn)", supply: 180, install: 50 },
        { name: "زر إطلاق يدوي للغاز", supply: 120, install: 40 },
        { name: "خزانة اسطوانات غاز (Cylinder Rack)", supply: 1200, install: 250 },
        { name: "وزن الكشف عن التسرب (Cylinder Scale)", supply: 450, install: 80 }
      ]
    }
  }
};

const LABOR_ADVICE = [
  "التكلفة الحقيقية للعامل = الراتب الشهري ÷ 26 يوم عمل، أضف عليها نسبة السكن والمواصلات والتأمين الصحي (عادة 30-40% من الراتب).",
  "أضف البدلات اليومية والمواد الاستهلاكية الخاصة بالعاملين (قفازات، ملابس عمل، أحذية أمان).",
  "نسبة فاقد الإنتاجية 15-20% بسبب الموافقات والانتظار في الموقع.",
  "التركيب المعتاد: كاشف/نقطة إنذار خلال 45-60 دقيقة للفني المدرب، نقطة استدعاء خلال 30 دقيقة.",
  "تركيب الرشاش: 25-40 دقيقة للرشاش الواحد شاملاً لحم السقف وتجهيز القاعدة.",
  "لحام وتركيب ماسورة قطر 2 بوصة: تقريباً 1.5-2 ساعة للمتر الواحد (قطع + لحم + عزل اختبار ضغط).",
  "يشمل متوسط التكلفة اليومية للفني الميداني مبلغ إضافي لضمان الجودة والإشراف.",
  "للأعمال الكبيرة، عادةً يحسب المقاولون التركيب بنسبة 25-40% من تكلفة الأجهزة."
];

const CABLE_ESTIMATE_PER_DEVICE = 15;
const CABLE_PRICE_PER_METER = 8;
